/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FunRouteImport } from './routes/fun'
import { Route as HowToBeSmarterThanAnAiRouteImport } from './routes/how-to-be-smarter-than-an-ai'
import { Route as SurpriseRouteImport } from './routes/surprise'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiRoastRouteImport } from './routes/api/roast'
import { Route as HorrorIndexRouteImport } from './routes/horror.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ApiPublicProjectDocRouteImport } from './routes/api/public/project-doc'
import { Route as ApiPublicProjectFileSplatRouteImport } from './routes/api/public/project-file.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FunRoute = FunRouteImport.update({
  id: '/fun',
  path: '/fun',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToBeSmarterThanAnAiRoute = HowToBeSmarterThanAnAiRouteImport.update({
  id: '/how-to-be-smarter-than-an-ai',
  path: '/how-to-be-smarter-than-an-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SurpriseRoute = SurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiRoastRoute = ApiRoastRouteImport.update({
  id: '/api/roast',
  path: '/api/roast',
  getParentRoute: () => rootRouteImport,
} as any)
const HorrorIndexRoute = HorrorIndexRouteImport.update({
  id: '/horror/',
  path: '/horror/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectDocRoute = ApiPublicProjectDocRouteImport.update({
  id: '/api/public/project-doc',
  path: '/api/public/project-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectFileSplatRoute =
  ApiPublicProjectFileSplatRouteImport.update({
    id: '/api/public/project-file/$',
    path: '/api/public/project-file/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/fun': typeof FunRoute
  '/how-to-be-smarter-than-an-ai': typeof HowToBeSmarterThanAnAiRoute
  '/surprise': typeof SurpriseRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/roast': typeof ApiRoastRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/horror/': typeof HorrorIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/project-doc': typeof ApiPublicProjectDocRoute
  '/api/public/project-file/$': typeof ApiPublicProjectFileSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/fun': typeof FunRoute
  '/how-to-be-smarter-than-an-ai': typeof HowToBeSmarterThanAnAiRoute
  '/surprise': typeof SurpriseRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/roast': typeof ApiRoastRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/horror': typeof HorrorIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/public/project-doc': typeof ApiPublicProjectDocRoute
  '/api/public/project-file/$': typeof ApiPublicProjectFileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/fun': typeof FunRoute
  '/how-to-be-smarter-than-an-ai': typeof HowToBeSmarterThanAnAiRoute
  '/surprise': typeof SurpriseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/roast': typeof ApiRoastRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/horror/': typeof HorrorIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/project-doc': typeof ApiPublicProjectDocRoute
  '/api/public/project-file/$': typeof ApiPublicProjectFileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/fun'
    | '/how-to-be-smarter-than-an-ai'
    | '/surprise'
    | '/admin'
    | '/api/roast'
    | '/projects/$slug'
    | '/horror/'
    | '/projects/'
    | '/api/public/project-doc'
    | '/api/public/project-file/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/fun'
    | '/how-to-be-smarter-than-an-ai'
    | '/surprise'
    | '/admin'
    | '/api/roast'
    | '/projects/$slug'
    | '/horror'
    | '/projects'
    | '/api/public/project-doc'
    | '/api/public/project-file/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/fun'
    | '/how-to-be-smarter-than-an-ai'
    | '/surprise'
    | '/_authenticated/admin'
    | '/api/roast'
    | '/projects/$slug'
    | '/horror/'
    | '/projects/'
    | '/api/public/project-doc'
    | '/api/public/project-file/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FunRoute: typeof FunRoute
  HowToBeSmarterThanAnAiRoute: typeof HowToBeSmarterThanAnAiRoute
  SurpriseRoute: typeof SurpriseRoute
  ApiRoastRoute: typeof ApiRoastRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  HorrorIndexRoute: typeof HorrorIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicProjectDocRoute: typeof ApiPublicProjectDocRoute
  ApiPublicProjectFileSplatRoute: typeof ApiPublicProjectFileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun': {
      id: '/fun'
      path: '/fun'
      fullPath: '/fun'
      preLoaderRoute: typeof FunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-be-smarter-than-an-ai': {
      id: '/how-to-be-smarter-than-an-ai'
      path: '/how-to-be-smarter-than-an-ai'
      fullPath: '/how-to-be-smarter-than-an-ai'
      preLoaderRoute: typeof HowToBeSmarterThanAnAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surprise': {
      id: '/surprise'
      path: '/surprise'
      fullPath: '/surprise'
      preLoaderRoute: typeof SurpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/roast': {
      id: '/api/roast'
      path: '/api/roast'
      fullPath: '/api/roast'
      preLoaderRoute: typeof ApiRoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horror/': {
      id: '/horror/'
      path: '/horror'
      fullPath: '/horror/'
      preLoaderRoute: typeof HorrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-doc': {
      id: '/api/public/project-doc'
      path: '/api/public/project-doc'
      fullPath: '/api/public/project-doc'
      preLoaderRoute: typeof ApiPublicProjectDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-file/$': {
      id: '/api/public/project-file/$'
      path: '/api/public/project-file/$'
      fullPath: '/api/public/project-file/$'
      preLoaderRoute: typeof ApiPublicProjectFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FunRoute: FunRoute,
  HowToBeSmarterThanAnAiRoute: HowToBeSmarterThanAnAiRoute,
  SurpriseRoute: SurpriseRoute,
  ApiRoastRoute: ApiRoastRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  HorrorIndexRoute: HorrorIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicProjectDocRoute: ApiPublicProjectDocRoute,
  ApiPublicProjectFileSplatRoute: ApiPublicProjectFileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
